AllCops:
  TargetRubyVersion: 2.3

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false
